# © 2025 Dowek Analytics Ltd.
# Oracle Samuel - Backend API Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-backend
  namespace: oracle-samuel
  labels:
    app: oracle-backend
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oracle-backend
  template:
    metadata:
      labels:
        app: oracle-backend
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: backend
        image: ghcr.io/dowek-analytics/oracle-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: oracle-config
        - secretRef:
            name: oracle-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: models
          mountPath: /app/models
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: models-pvc
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: oracle-backend
  namespace: oracle-samuel
  labels:
    app: oracle-backend
spec:
  type: ClusterIP
  selector:
    app: oracle-backend
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: oracle-samuel
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: oracle-samuel
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: oracle-backend-hpa
  namespace: oracle-samuel
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oracle-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

