# © 2025 Dowek Analytics Ltd.
# Oracle Samuel - Frontend Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-frontend
  namespace: oracle-samuel
  labels:
    app: oracle-frontend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oracle-frontend
  template:
    metadata:
      labels:
        app: oracle-frontend
        version: v1
    spec:
      containers:
      - name: frontend
        image: ghcr.io/dowek-analytics/oracle-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
          name: http
        env:
        - name: BACKEND_URL
          value: "http://oracle-backend"
        envFrom:
        - configMapRef:
            name: oracle-config
        - secretRef:
            name: oracle-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: oracle-frontend
  namespace: oracle-samuel
  labels:
    app: oracle-frontend
spec:
  type: ClusterIP
  selector:
    app: oracle-frontend
  ports:
  - name: http
    port: 80
    targetPort: 8501
    protocol: TCP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: oracle-frontend-hpa
  namespace: oracle-samuel
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oracle-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

